---
title: "00_learn_ggmap"
author: "Author: [Steve, Yu](https://github.com/littlefish0331)"
date: "`r Sys.setlocale('LC_TIME', 'English'); format(Sys.time(), '%Y %b %d %a, %H:%M:%S')`" 
output:
  rmdformats::readthedown:
    css: style.css
    self_contained: TRUE
    thumbnails: FALSE
    lightbox: TRUE
    gallery: FALSE
    highlight: tango #探戈橘
    code_folding: show
    toc_depth: 3
    
---

```{r setup, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
rm(list = ls()); gc()
library(knitr)
library(kableExtra)
library(dplyr)
library(data.table)
library(ggmap)
knitr::opts_chunk$set(
	# 這邊是針對所有chunk的設定
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# reference

[dkahle/ggmap: A package for plotting maps in R with ggplot2](https://github.com/dkahle/ggmap)

---

# get location latlon range

[r - Is ggmap broken? Basic qmap() produces "arguments imply differing number of rows: 0,1" - Stack Overflow](https://stackoverflow.com/questions/52704695/is-ggmap-broken-basic-qmap-produces-arguments-imply-differing-number-of-rows)

```{r}
library(tmaptools)
# geocode_OSM("Taiwan")
# $query
# [1] "Taiwan"
# 
# $coords
#         x         y 
# 120.98202  23.97394 
# 
# $bbox
#      xmin      ymin      xmax      ymax 
# 114.35932  10.37301 122.29700  26.43722 

# geocode_OSM("Hsinchu")
# $query
# [1] "Hsinchu"
# 
# $coords
#         x         y 
# 120.96868  24.80663 
# 
# $bbox
#      xmin      ymin      xmax      ymax 
# 120.87942  24.71257 121.03354  24.85321
```

---

# README

```{r}
# American
us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
get_stamenmap(us, zoom = 4, maptype = "toner-lite") %>% ggmap()
get_stamenmap(us, zoom = 4, maptype = "terrain") %>% ggmap()
```

```{r}
# taiwan
tw <- c(left = 117.35932, bottom = 20.37301, right = 123.29700, top = 26.43722)
get_stamenmap(tw, zoom = 7, maptype = "toner-lite") %>% ggmap() 
get_stamenmap(tw, zoom = 7, maptype = "terrain") %>% ggmap(extent = "device") 
get_stamenmap(tw, zoom = 7, maptype = "terrain") %>% ggmap() 
```

```{r}
library(forcats)

# define helper
`%notin%` <- function(lhs, rhs) !(lhs %in% rhs)

# reduce crime to violent crimes in downtown houston
violent_crimes <- crime %>% 
  filter(
    offense %notin% c("auto theft", "theft", "burglary"),
    -95.39681 <= lon & lon <= -95.34188,
     29.73631 <= lat & lat <=  29.78400
  ) %>% 
  mutate(
    offense = fct_drop(offense),
    offense = fct_relevel(offense, c("robbery", "aggravated assault", "rape", "murder"))
  )

# use qmplot to make a scatterplot on a map
qmplot(x = lon, y = lat, data = violent_crimes, 
       maptype = "toner-lite", 
       color = I("red"))
#  Using zoom = 14...
#  Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

```{r}
qmplot(lon, lat, data = violent_crimes, 
       maptype = "toner-lite", geom = "density2d", 
       color = I("red"))
```

```{r}
robberies <- violent_crimes %>% filter(offense == "robbery")

qmplot(lon, lat, data = violent_crimes, 
       geom = "blank", 
       zoom = 14, 
       maptype = "toner-background", 
       darken = .7, 
       legend = "topleft") +
  stat_density_2d(mapping = aes(fill = ..level..), geom = "polygon", 
                  alpha = .3, color = NA) +
  scale_fill_gradient2("Robbery\nPropensity", 
                       low = "white", mid = "yellow", high = "red", 
                       midpoint = 650)
#  Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

```{r}
qmplot(x = lon, y = lat, data = violent_crimes, 
       maptype = "toner-background", 
       color = offense) + 
  facet_wrap(~ offense)
#  Using zoom = 14...
#  Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```

```{r}
maps_static_api_key <- 
  read.table("E:/API_key/google_api_key.txt", header = T, stringsAsFactors = F) %>%
  setDT() %>% .[API_name=="maps_static", API_key]
# register_google(key = maps_static_api_key)
# google_key()
# has_google_key()
get_googlemap("taiwan", zoom = 7, scale = 2, maptype = "roadmap", archiving = T) %>% ggmap()
```


---

# END

